name: Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra_aws

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.2
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Setup Terraform Backend
        id: backend
        run: |
          cat > backend.tf << EOF
          terraform {
              cloud {
                  organization = "${{ secrets.TF_CLOUD_ORGANIZATION }}"
                  workspaces {
                  name = "${{ secrets.TF_CLOUD_WORKSPACE_AUTO_WORKSPACE }}"
                  }
              }
          }
          EOF

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -lock=false

      - name: Terraform Apply
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'deploy')
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'destroy')
        run: terraform destroy -auto-approve
